replicaCount: 1

image:
  repository: "docker.io/muhammadnaeem42/application4"  # Your Docker Hub image name
  pullPolicy: Always
  tag: "latest"


service:
  name: application3
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  name: application3-ingress
  path: /
  hosts:
    - application3.local
  tls: []
