apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-application3
  labels:
    app: application3
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: application3
  template:
    metadata:
      labels:
        app: application3
    spec:
      containers:
        - name: application3
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}

