replicaCount: 1

image:
  repository: "docker.io/muhammadnaeem42/application3"  # Your Docker Hub image name
  pullPolicy: Always
  tag: v1.1.1  

service:
  name: application3
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  name: application3-ingress
  path: /
  hosts:
    - application3.local
  tls: []
